name: ci
on:
  push:
    branches:
      - main

# Environment
env:
  CI: true
  NODE_VERSION: 10.x
  PYTHON_VERSION: 3.x
          
jobs:
   
   
  deploy:
    runs-on: cirrusci/flutter:1.20.1
    steps:
      - uses: actions/checkout@v2
      - run: flutter config --enable-web
      - run: flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true
      - uses:
