name: ci
on:
  push:
    branches:
      - master

# Environment
env:
  CI: true
  NODE_VERSION: 10.x
  PYTHON_VERSION: 3.x
          
jobs:
   
   
  build:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/flutter:1.20.1

    steps:
      - uses: actions/checkout@v2
      - run: flutter config --enable-web
      - run: flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true

      - name: GH pages deploy
        uses: Cecilapp/GitHub-Pages-deploy@3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # A verified email.
          email: penlipenkovladislav@gmail.com
          # Where static files are.
          build_dir: build/web
          # Which branch to push files.
          branch: gh-pages
          # The custom domain name.
